### ISSUE TITLE
alpine-deno:1.7.5

### ISSUE THREAD

**Issue by asantos00** [denoland/deno_docker#116]
Hi there,

First of all thanks for providing this image, this is my go-to solution when using deno on docker 🙌 

I was wondering if you could build and push a tag for version 1.7.5 of Deno? Currently the latest 1.7.* that exists is 1.7.2.

Let me know if I can help

**Comment by asantos00** [comment]
No worries, I'm not desperate, I was just used to have docker images in sync with the Deno versions, and then started getting warnings that I couldn't fetch some of the images 🤔 

Thank you so much!

**Comment by lucacasonato** [comment]
Latest release is 1.10.3 now
