### ISSUE TITLE
Pin all dependency versions, provide `alpine-3.13`

### ISSUE THREAD

**Issue by mitranim** [denoland/deno_docker#152]
Just spent a while headbutting weird CI failures. The ultimate solution was to rip apart and copy-paste `alpine.dockerfile`, but with the pinned version of `FROM frolvlad/alpine-glibc:alpine-3.13`. Because in this repo the dependency version is not pinned, newer images used `3.14` which caused weird edge case breakage in our build.

I'm not sure how this should be versioned. In our case, we want newer Deno but older Alpine. No specific recommendation here, just letting you know about the problem for now.

**Comment by wperron** [comment]
I have no issue just pinning the alpine version to 3.13, especially given that the distroless version uses a pinned 3.12 alpine as a pre-build step to download the deno binary.
