### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by malaxmimdkm** [denoland/deno_docker#156]
$ docker build -t app . && docker run -it --init -p 1993:1993 app
[+] Building 7.7s (8/10)
 => [internal] load build definition from Dockerfile                                                                                        0.0s 
 => => transferring dockerfile: 32B                                                                                                         0.0s 
 => [internal] load .dockerignore                                                                                                           0.0s 
 => => transferring context: 2B                                                                                                             0.0s 
 => [internal] load metadata for docker.io/denoland/deno:1.13.0                                                                             1.3s 
 => [internal] load build context                                                                                                           0.0s 
 => => transferring context: 114B                                                                                                           0.0s 
 => [1/6] FROM docker.io/denoland/deno:1.13.0@sha256:5a95c2eb20256447ccd51b4d57560710bd6ea57ba16ea5c57ff04dcb49da752c                       0.0s 
 => CACHED [2/6] WORKDIR /app                                                                                                               0.0s 
 => CACHED [3/6] COPY deps.ts .                                                                                                             0.0s 
 => ERROR [4/6] RUN deno cache deps.ts                                                                                                      6.2s 
------
 > [4/6] RUN deno cache deps.ts:
#8 0.465 Download https://deno.land/std@0.77.0/http/server.ts
#8 1.724 Download https://deno.land/std@0.77.0/async/mod.ts
#8 1.724 Download https://deno.land/std@0.77.0/io/bufio.ts
#8 1.724 Download https://deno.land/std@0.77.0/_util/assert.ts
#8 1.725 Download https://deno.land/std@0.77.0/http/_io.ts
#8 1.725 Download https://deno.land/std@0.77.0/encoding/utf8.ts
#8 2.332 Download https://deno.land/std@0.77.0/async/delay.ts
#8 2.332 Download https://deno.land/std@0.77.0/async/deferred.ts
#8 2.332 Download https://deno.land/std@0.77.0/async/mux_async_iterator.ts
#8 2.333 Download https://deno.land/std@0.77.0/async/pool.ts
#8 2.592 Download https://deno.land/std@0.77.0/http/http_status.ts
#8 2.592 Download https://deno.land/std@0.77.0/textproto/mod.ts
#8 2.869 Download https://deno.land/std@0.77.0/bytes/mod.ts
#8 3.189 Check file:///app/deps.ts
#8 6.120 error: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.  
#8 6.120   Type 'string' is not assignable to type '"UnexpectedEof"'.
#8 6.120   name = "PartialReadError";
#8 6.120   ~~~~
#8 6.120     at https://deno.land/std@0.77.0/io/bufio.ts:27:3
------
executor failed running [/bin/sh -c deno cache deps.ts]: exit code: 1

**Comment by bartlomieju** [comment]
The images have just been updated to 1.13.1 which should fix this error, please try again.
