### ISSUE TITLE
Add `tini` to container

### ISSUE THREAD

**Issue by felipecrs** [denoland/deno_docker#161]
While the `README` suggests to use `docker run --init`, the bullet-proof approach would be to bundling `tini` in the container itself, as stated in the docker best practices guides for the official images:

https://github.com/docker-library/official-images#init

Its binary is extremely _tiny_ and should not cause any noticeable increase in the size of the docker image.

**Comment by wperron** [comment]
Very much in favor, I actually just hit the issue of not handling SIGTERM on a demo Docker container, `--init` is super easy to forget or simply not know about.
