### ISSUE TITLE
bin tag not found

### ISSUE THREAD

**Issue by hayd** [denoland/deno_docker#177]
Is the expectation this tag should be [published on docker hub](https://github.com/denoland/deno_docker#using-your-own-base-image)?

https://hub.docker.com/r/denoland/deno/tags?page=1&ordering=last_updated&name=bin

**Comment by wperron** [comment]
Yup, we just merged the changed not too long after 1.13.2, and then the merge window for 1.14 opened which is typically a bit longer, it'll be published with 1.14 soon.
