### ISSUE TITLE
Deno Jupyter image

### ISSUE THREAD

**Issue by apowers313** [denoland/deno_docker#195]
I’d like to make a Deno Jupyter image. It would use Deno Ubuntu as the base, similar to the [Jupyter docker images](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html), then install Python, Jupyter, and Jupyter extensions — similar to [this image](https://github.com/apowers313/nhai-docker-base/blob/master/Dockerfile#L44).

This would be useful for Jupyter integration testing using [papermill](https://papermill.readthedocs.io/en/latest/) and cell tags, similar to [this](https://github.com/apowers313/nhai/tree/master/test/integration).

**Comment by davidchieregato** [comment]
In the last 2 years is there any officially supported/suggested Jupyter Image for Deno?

**Comment by bartlomieju** [comment]
Deno now ships with official Jupyter kernel (https://docs.deno.com/runtime/manual/tools/jupyter) so the already provided Docker images can be used.
