### ISSUE TITLE
1.20.2 image not published

### ISSUE THREAD

**Issue by treethought** [denoland/deno_docker#215]
Not sure if what the CI process is and if this was intended or not, but the 1.20.2 image was not pushed to the registry https://github.com/denoland/deno_docker/runs/5674347456?check_suite_focus=true

I looked at the previous release and the `Pushed named images` job did run for the same version bump diff for 1.20.1
https://github.com/denoland/deno_docker/runs/5580064062?check_suite_focus=true

**Comment by danopia** [comment]
The creation of a git tag is what drives the docker push, and it isn't automated yet.

The tag has been created now for 1.20.2, see: https://github.com/denoland/deno_docker/pull/214#issuecomment-1078514517
