### ISSUE TITLE
Containers for 1.30.0 have Deno CLI version 1.29.4

### ISSUE THREAD

**Issue by erichardson-lee** [denoland/deno_docker#266]
![image](https://user-images.githubusercontent.com/77331675/214859769-aa6b1773-58e3-49f0-9073-16aeed6bc46d.png)

`> docker run --rm -it denoland/deno:alpine-1.30.0 /bin/sh`

As shown above, found this when I was getting a type error on my testing step, due to passing a ReadableStream into Deno.writeFile (A new feature in 1.30.0)

**Comment by erichardson-lee** [comment]
Also on debian
![image](https://user-images.githubusercontent.com/77331675/214861096-24bc4bcd-19ad-40d6-8f06-c8434507c2dd.png)

**Comment by bartlomieju** [comment]
Sorry for the problem. It should be fixed now.
