### ISSUE TITLE
Add release workflow

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_docker#267]
Similar to other repos that take part in a release of the Deno CLI, we should have a release workflow in this repository.

The workflow could be based on https://github.com/denoland/deno_std/blob/main/.github/workflows/version_bump.yml

I think we should add `version.ts` file that has following content:
```ts
const VERSION = "1.30.0";
```
A release workflow would look up this file and bump the version accordingly depending if the release is a patch release or minor release. Then iterate over files in the repository and replace previous version with the new version. We should also have an assertion for how many times a version was replaced and it should be checked that expected number of replacements was made.

**Comment by dsherret** [comment]
Seems we can use @kt3k's https://github.com/kt3k/bmp in the workflow. It looks like we could be precise about each file to modify.
