### ISSUE TITLE
Add ARM64 platform to docker images

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno_docker#337]
Now that we're building ARM64/Linux, we should be publishing both AMD64 and ARM64 images for each container type.

**Comment by LukeChannings** [comment]
<img width="1369" alt="Screenshot 2024-02-15 at 11 29 33" src="https://github.com/denoland/deno_docker/assets/461449/f049cbb6-e134-471f-ab10-e784231fce57">

I think this can be closed now!
