### ISSUE TITLE
1.45.1 tag is missing on Docker Hub

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno_docker#380]
https://hub.docker.com/r/denoland/deno/tags

There is `debian-1.45.1`, but no `1.45.1` and `latest` is also outdated. CI fails when I try to use it:

> ERROR: Job failed: failed to pull image "denoland/deno:1.45.1" with specified policies [always]: Error response from daemon: manifest for denoland/deno:1.45.1 not found: manifest unknown: manifest unknown (manager.go:250:0s)

https://gitlab.com/soapbox-pub/ditto/-/jobs/7331214333

**Comment by bartlomieju** [comment]
This should be fixed now
